  `woid` decimal, 
  `wo_code` string, 
  `incident_locator` string, 
  `source_type` string, 
  `wo_est_effort` decimal, 
  `gpo_wo_est_overhead_hours` decimal, 
  `wo_created` timestamp, 
  `sr_asset_name` string, 
  `country` string, 
  `wo_proc_scope` decimal, 
  `wo_uofm` string, 
  `func_class` string, 
  `effort_type` string, 
  `reporting_country` string, 
  `wo_completed` timestamp, 
  `partition_name` string, 
  `gpo_uofm` string, 
  `wo_due_date` timestamp, 
  `gpo_scope` decimal, 
  `wsgroup` string, 
  `work_db` string, 
  `wo_compl` decimal, 
  `ipl_parent` string, 
  `ipl` string, 
  `exec_dtl` string, 
  `workstream` string, 
  `rmc_planned_workstream` string, 
  `wo_act_sum` decimal, 
  `to_act_hrs` decimal, 
  `to_act_scope` decimal, 
  `to_effort` decimal, 
  `to_plan_scope` decimal, 
  `scope_agg_scope` decimal, 
  `region` string, 
  `region_sub` string, 
  `map_product` string, 
  `hl_dept` string, 
  `to_act_coding_hrs` decimal, 
  `project_id` decimal, 
  `uofm_type` string, 
  `compl_dte_fiscal_pd` string, 
  `pl` string, 
  `pl_id` decimal, 
  `pl_obs` string, 
  `pm` string, 
  `pm_id` decimal, 
  `portfolio` string, 
  `work_order_descr` string, 
  `qa_passed_to_cnt` decimal, 
  `qa_check_to_cnt` decimal, 
  `qil_passed_to_cnt` decimal, 
  `qil_checked_to_cnt` decimal, 
  `mpi` decimal)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://explorer-datasets-sources-prod/parquet_sources/bearing_work_orders_full_10_22_2025_20_00_02/'
TBLPROPERTIES (
  'classification'='parquet', 
  'compressionType'='none', 
  'projection.enabled'='false', 
  'typeOfData'='file')
