  `region` string, 
  `iso_code` string, 
  `country` string, 
  `admin_level2_name` string, 
  `admin_level3_name` string, 
  `admin_level4_name` string, 
  `admin_level5_name` string, 
  `condition_pvid` bigint, 
  `condition_id` bigint, 
  `condition_type_id` bigint, 
  `condition_type` string, 
  `traffic_sign_type` string, 
  `end_of_link` string, 
  `cond_last_updated` timestamp, 
  `data_source` bigint, 
  `applies_to_autos` boolean, 
  `date_time_modifier` string, 
  `link_id` bigint, 
  `link_pvid` bigint, 
  `functional_class` bigint, 
  `intersection_category` string, 
  `bridge` boolean, 
  `tunnel` boolean, 
  `urban` boolean, 
  `access_autos` boolean, 
  `is_ramp` boolean, 
  `is_paved` boolean, 
  `has_controlled_access` boolean, 
  `is_motorway` boolean, 
  `is_multi_digitized` boolean, 
  `is_limited_access_road` boolean, 
  `is_poi_access` boolean, 
  `is_parking_lot_road` boolean, 
  `is_public_access` boolean, 
  `is_race_track` boolean, 
  `link_length_meters` double, 
  `link_geometry` string, 
  `sign_node_pvid` bigint, 
  `sign_node_id` bigint, 
  `sign_lat` double, 
  `sign_lon` double, 
  `prev_shape_lat` double, 
  `prev_shape_lon` double, 
  `rdm_type` string, 
  `rdm_time_override` string, 
  `traffic_signal_sign_location` string, 
  `traffic_signal_ng_importance` bigint, 
  `traffic_sign_duration` string, 
  `traffic_sign_duration_language_code` string, 
  `traffic_sign_prewarning` string, 
  `traffic_sign_prewarning_language_code` string, 
  `traffic_sign_applicable_truck` boolean, 
  `traffic_sign_applicable_truck_over35tn` boolean, 
  `traffic_sign_applicable_bus` boolean, 
  `traffic_sign_applicable_trailer` boolean, 
  `traffic_sign_applicable_motor_home` boolean, 
  `traffic_sign_applicable_motorcycle` boolean, 
  `traffic_sign_validity_time` string, 
  `traffic_sign_validity_time_language_code` string, 
  `traffic_sign_general_warning_type` string, 
  `traffic_sign_value` string, 
  `traffic_sign_value_language_code` string, 
  `traffic_sign_weather_type` string, 
  `traffic_sign_ng_importance` bigint, 
  `traffic_sign_applicable_vehicles` bigint, 
  `railway_crossing_type` string, 
  `blackspot_source` string, 
  `pdm_type` string, 
  `pdm_time_override` string, 
  `nav_link_count` bigint, 
  `node_highest_importance_fc` decimal, 
  `node_lowest_importance_fc` decimal, 
  `railroad_node` string, 
  `bearing_rmob` double, 
  `cond_creation_date` timestamp)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://explorer-datasets-sources-prod/parquet_sources/conditions_single_link_with_eol_weekly_10_26_2025_12_00_02/'
TBLPROPERTIES (
  'classification'='parquet', 
  'compressionType'='none', 
  'projection.enabled'='false', 
  'typeOfData'='file')
