  `region` string, 
  `country` string, 
  `admin_level2_name` string, 
  `admin_level3_name` string, 
  `admin_level4_name` string, 
  `admin_level5_name` string, 
  `link_pvid` string, 
  `link_rmob_id` bigint, 
  `link_last_updated` timestamp, 
  `functional_class` string, 
  `speed_limit` string, 
  `lane_category` string, 
  `speed_category` string, 
  `road_class` string, 
  `travel_direction` string, 
  `intersection_category` string, 
  `low_mobility` string, 
  `bua_road` string, 
  `coverage_indicator` string, 
  `is_long_haul` boolean, 
  `auto_access` boolean, 
  `bus_access` boolean, 
  `taxi_access` boolean, 
  `motorcycle_access` boolean, 
  `carpool_access` boolean, 
  `pedestrian_access` boolean, 
  `truck_access` boolean, 
  `through_traffic_access` boolean, 
  `delivery_access` boolean, 
  `emergency_vehicle_access` boolean, 
  `is_ramp` boolean, 
  `is_paved` boolean, 
  `is_private` boolean, 
  `is_tollway` boolean, 
  `is_poi_access` boolean, 
  `has_controlled_access` boolean, 
  `is_motorway` boolean, 
  `is_mutiple_digitized` boolean, 
  `is_express_lane` boolean, 
  `is_reversible` boolean, 
  `is_carpool_road` boolean, 
  `is_parking_lot_road` boolean, 
  `has_public_access` boolean, 
  `is_delivery_road` boolean, 
  `is_limited_access_road` boolean, 
  `is_boat_ferry` boolean, 
  `is_rail_ferry` boolean, 
  `total_kms` double, 
  `speed_limit_last_updated` timestamp, 
  `speed_cat_last_updated` timestamp, 
  `geometry_last_updated` timestamp, 
  `coverage_indicator_last_updated` timestamp, 
  `dot_last_updated` timestamp, 
  `link_geometry` string, 
  `latitude` double, 
  `longitude` double, 
  `is_divider_legal` boolean, 
  `is_inprocess_data` boolean, 
  `is_scenic` boolean, 
  `is_transport_verified` boolean, 
  `has_point_address` string, 
  `has_address_range` string, 
  `has_road_name` string, 
  `has_four_wheel_drive` boolean, 
  `has_historical_4wd` boolean, 
  `adas_category` string, 
  `has_lanes` boolean, 
  `lane_types` string, 
  `lane_access` string, 
  `country_iso_code` string, 
  `admin_l1_pvid` bigint, 
  `admin_l2_pvid` bigint, 
  `admin_l3_pvid` bigint, 
  `level10_tileid` bigint, 
  `level12_tileid` bigint, 
  `level14_tileid` bigint, 
  `level16_tileid` bigint)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://explorer-datasets-sources-prod/parquet_sources/navigable_road_attributes_sar_bw_2024_12_30_2024_00_00_07/'
TBLPROPERTIES (
  'classification'='parquet', 
  'compressionType'='none', 
  'projection.enabled'='false', 
  'typeOfData'='file')
