  `region` string, 
  `in_link_id` bigint, 
  `out_link_id` bigint, 
  `in_link_pvid` string, 
  `out_link_pvid` string, 
  `in_speed` decimal, 
  `out_speed` decimal, 
  `in_spd_lm_src` string, 
  `out_spd_lm_src` string, 
  `in_speed_direction` string, 
  `out_speed_direction` string, 
  `node_pvid` bigint, 
  `node_type` string, 
  `dir_travel` string, 
  `in_speed_limit_date` decimal, 
  `out_speed_limit_date` decimal, 
  `in_func_class` decimal, 
  `out_func_class` decimal, 
  `longitude` double, 
  `latitude` double, 
  `in_next_shape_lon` double, 
  `in_next_shape_lat` double, 
  `out_next_shape_lon` double, 
  `out_next_shape_lat` double, 
  `iso_code` string, 
  `admin_code_1` string, 
  `admin_code_2` string, 
  `admin_code_3` string, 
  `in_bua_road` string, 
  `out_bua_road` string, 
  `in_urban` boolean, 
  `out_urban` boolean, 
  `in_intersection_category` string, 
  `out_intersection_category` string, 
  `in_is_paved` boolean, 
  `out_is_paved` boolean, 
  `in_is_ramp` boolean, 
  `out_is_ramp` boolean, 
  `in_is_ctrl_access` boolean, 
  `out_is_ctrl_access` boolean, 
  `in_is_motorway` boolean, 
  `out_is_motorway` boolean, 
  `in_is_limited_access` boolean, 
  `out_is_limited_access` boolean, 
  `in_is_mtdg` boolean, 
  `out_is_mtdg` boolean, 
  `in_lane_category` string, 
  `out_lane_category` string, 
  `in_bridge` boolean, 
  `out_bridge` boolean, 
  `in_tunnel` boolean, 
  `out_tunnel` boolean, 
  `in_is_poi_access` boolean, 
  `out_is_poi_access` boolean, 
  `left_admin_rmob_id` bigint, 
  `right_admin_rmob_id` bigint, 
  `admin_level1_name` string, 
  `admin_level2_name` string, 
  `admin_level3_name` string, 
  `admin_level4_name` string, 
  `admin_level5_name` string, 
  `in_link_last_updated` timestamp, 
  `out_link_last_updated` timestamp, 
  `in_speed_limit_last_updated` timestamp, 
  `out_speed_limit_last_updated` timestamp, 
  `in_speed_cat_last_updated` timestamp, 
  `out_speed_cat_last_updated` timestamp, 
  `data_freshness` date, 
  `link_count_at_node` bigint, 
  `in_bearing_rmob` double, 
  `out_bearing_rmob` double)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://explorer-datasets-sources-prod/parquet_sources/rmob_bw_speed_limit_changes_10_26_2025_14_00_02/'
TBLPROPERTIES (
  'classification'='parquet', 
  'compressionType'='none', 
  'projection.enabled'='false', 
  'typeOfData'='file')
