  `region` string, 
  `iso_code` string, 
  `country` string, 
  `admin_level2_name` string, 
  `admin_level3_name` string, 
  `admin_level4_name` string, 
  `admin_level5_name` string, 
  `admin_l1_admin_code` string, 
  `admin_l2_admin_code` string, 
  `admin_l3_admin_code` string, 
  `admin_l4_admin_code` string, 
  `admin_l5_admin_code` string, 
  `admin_l1_pvid` bigint, 
  `admin_l2_pvid` bigint, 
  `admin_l3_pvid` bigint, 
  `admin_l4_pvid` bigint, 
  `admin_l5_pvid` bigint, 
  `link_rmob_id` bigint, 
  `link_pvid` string, 
  `left_admin_rmob_id` bigint, 
  `right_admin_rmob_id` bigint, 
  `ref_node_pvid` bigint, 
  `nref_node_pvid` bigint, 
  `link_last_updated` timestamp, 
  `from_ref_speed_limit` decimal, 
  `to_ref_speed_limit` decimal, 
  `speed_limit_source` string, 
  `speed_limit_date` decimal, 
  `speed_limit_last_updated` timestamp, 
  `speed_category` string, 
  `speed_cat_last_updated` timestamp, 
  `lane_category` string, 
  `functional_class` decimal, 
  `travel_direction` string, 
  `intersection_category` string, 
  `bua_road` string, 
  `bridge` boolean, 
  `tunnel` boolean, 
  `urban` boolean, 
  `access_autos` boolean, 
  `is_ramp` boolean, 
  `is_paved` boolean, 
  `has_controlled_access` boolean, 
  `is_motorway` boolean, 
  `is_multi_digitized` boolean, 
  `is_limited_access_road` boolean, 
  `is_poi_access` boolean, 
  `is_parking_lot_road` boolean, 
  `is_public_access` boolean, 
  `is_race_track` boolean, 
  `link_length_meters` decimal, 
  `link_geometry` string, 
  `latitude` double, 
  `longitude` double, 
  `data_freshness` date)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://explorer-datasets-sources-prod/parquet_sources/speed_limit_attributes_weekly_10_26_2025_10_00_02/'
TBLPROPERTIES (
  'classification'='parquet', 
  'compressionType'='none', 
  'projection.enabled'='false', 
  'typeOfData'='file')
